# Generated by Django 2.2.1 on 2019-07-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Dob', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
            ],
        ),
    ]
